### ISSUE TITLE
Tracking enabled

### ISSUE THREAD

**Issue by mcorner** [ptomasroos/react-native-idfa#12]
If you collect the IDFA you need to collect tracking enabled, right?  Or is that no longer a requirement?

**Comment by ptomasroos** [comment]
If you recall during submission? Then yes, using IDFA you need to enable that @mcorner

**Comment by mcorner** [comment]
But this repo doesn't seem to support it.  I could probably throw together a pull for this.

**Comment by ptomasroos** [comment]
Can you please state the question again @mcorner, didnt really understand it. Thought you mean during the review you where you answer Yes that IDFA is used in the app.

**Comment by mcorner** [comment]
I am referring to the "isAdvertisingTrackingEnabled" flag:
https://developer.apple.com/documentation/adsupport/asidentifiermanager/1614148-isadvertisingtrackingenabled

https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy
"If your app uses the ASIdentifierManager class, you must respect the value of its isAdvertisingTrackingEnabled property. "

**Comment by ptomasroos** [comment]
https://developer.apple.com/documentation/adsupport/asidentifiermanager/1614151-advertisingidentifier


Important
In iOS 10.0 and later, the value of advertisingIdentifier is all zeroes when the user has limited ad tracking.

**Comment by mcorner** [comment]
Yes, though if you target < 10 you should be collecting it.  And....Android has the same flag that this library does not pass: "isLimitAdTrackingEnabled()" http://www.androiddocs.com/google/play-services/id.html

**Comment by ptomasroos** [comment]
All right. Let me fix this for you tomorrow then. Takes a very little effort.

**Comment by ptomasroos** [comment]
235c0ea8df697d9a5102b85971a36d452a0e27e4
2a8f582255ef1f22a3a92fa17b255f59d6d356a5
