### ISSUE TITLE
Support Android SDK >= 16 ?

### ISSUE THREAD

**Issue by mikaoelitiana** [ptomasroos/react-native-idfa#13]
Hello, I need to support Android SDK 16 on an app using this library? Is there a particularu reason for `minSdkVersion 21`?

**Comment by ptomasroos** [comment]
Not really. I seen some people adapting to using the minSdkVersion from the parent project we could use that to make it better

**Comment by ptomasroos** [comment]
https://github.com/react-native-community/react-native-camera/commit/389c731bec16c2bd08eca439b4b97ce88a1170af#diff-7ae5a9093507568eabbf35c3b0665732

You can see the change over there, feel free to send a pull request

**Comment by ptomasroos** [comment]
This is now released on npm

**Comment by mikaoelitiana** [comment]
Thanks!!
