### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'PTRIDFA.getIDFA') (iOS)

### ISSUE THREAD

**Issue by Juliocbr** [ptomasroos/react-native-idfa#15]
When I run my app in iOS appears this error: 
TypeError: undefined is not an object (evaluating 'PTRIDFA.getIDFA')

I added AdSupport.framework to Link Binary with Libraries and also I run react-native link command.

ios version: 11.3.1

I have a podfile in my project (I don't know if this file generates this error)

**Comment by Juliocbr** [comment]
It seems that the command 'react-native link' does not install the library in ios project.

**Comment by afilp** [comment]
@Juliocbr I have the same problem in Android, not sure if the link is correct though.

**Comment by afilp** [comment]
@Juliocbr Thanks Julio, it works! (did not do the `pod install` before).

I now have the other problem (in Android) with the "@" character in the name. It does not compile the lib there due to this:   https://github.com/ptomasroos/react-native-idfa/issues/16

Do you have the same problem there?

**Comment by Juliocbr** [comment]
@afilp  I don't problems with the name in Android, but I guess it may be because of the gradle version in my android project, the solution could be as @alimek says, renaming the project: [https://github.com/yfuks/react-native-action-sheet/issues/25#issuecomment-396894474](Android Studio error #25)

**Comment by afilp** [comment]
@Juliocbr Seems like this is the way to go: https://github.com/ptomasroos/react-native-idfa/issues/19
