### ISSUE TITLE
Change project name

### ISSUE THREAD

**Issue by mcorner** [ptomasroos/react-native-idfa#16]
This will bite people eventually:

The project name '@ptomasroos/react-native-idfa' contains at least one of the following characters: [ , /, \, :, <, >, ", ?, *, |]. This has been deprecated and is scheduled to be removed in Gradle 5.0. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/4.4/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).

**Comment by afilp** [comment]
Note, they had the same problem (and solved it with renaming it):

https://github.com/yfuks/react-native-action-sheet/issues/25

https://github.com/yfuks/react-native-action-sheet/commit/258f41ec8b10e21a099f2224c7c283445a09ca1e

**Comment by ptomasroos** [comment]
Thanks @afilp,

will try to finish that, this week

**Comment by ptomasroos** [comment]
Resolved and published under a new package name https://www.npmjs.org/package/react-native-idfa
