### ISSUE TITLE
Android build doesn't works 

### ISSUE THREAD

**Issue by qvick1pro** [ptomasroos/react-native-idfa#21]
can you publish new release please?

That commit fix this issue https://github.com/ptomasroos/react-native-idfa/commit/330d2a507b4ea9ea7cb5af1df08154ceec94aad6

**Comment by ptomasroos** [comment]
Sure thing!
Will introduce it under a new package. But I wont have time until next week.

You can always point to that commit through git

**Comment by ptomasroos** [comment]
Published as 3.0.0
