### ISSUE TITLE
android/build

### ISSUE THREAD

**Issue by hehex9** [ptomasroos/react-native-idfa#23]
The entire `android/build` directory is published to npm.
I think we should put it in the .npmignore file. 
The [package](https://registry.yarnpkg.com/@ptomasroos/react-native-idfa/-/react-native-idfa-2.1.0.tgz) size is 40M+ currently, which is not good.

**Comment by ptomasroos** [comment]
Thanks, i will fix this!

**Comment by ptomasroos** [comment]
Fixed in https://github.com/ptomasroos/react-native-idfa/commit/a2242070a14a68f0fa72373af9fbd598816520fd
