### ISSUE TITLE
Error in com.google.android.gms.ads

### ISSUE THREAD

**Issue by reemtariqq** [ptomasroos/react-native-idfa#24]
I got this error, however, I added the code where we force to use ver 17.0.0

  Process: com.pushnotification, PID: 15131
    java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
    * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
    * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
    * follow instructions here: https://goo.gl/h17b6x.                           *
    ******************************************************************************

**Comment by ptomasroos** [comment]
Can you please prepare a repro repo?

**Comment by reemtariqq** [comment]
I've added the version explicit at the dependencies , thank you
