### ISSUE TITLE
Adding google playservices check

### ISSUE THREAD

**Issue by ejkkan** [ptomasroos/react-native-idfa#28]
Hello!

Trying to make a pull request but get permissions denial.

Would it be possible for you to edit build.gradle dependencies with this:
implementation "com.google.android.gms:play-services-ads:${safeExtGet('googlePlayServicesVersion', '+')}" 

All the best,
Erik

**Comment by ptomasroos** [comment]
Any reason you can't use this which is in the README?

https://github.com/ptomasroos/react-native-idfa#changing-react-native-idfas-comgoogleandroidgmsplay-services-ads-version

**Comment by ejkkan** [comment]
My bad. Closing issue
