### ISSUE TITLE
Newest version not published to npm

### ISSUE THREAD

**Issue by Andruschenko** [ptomasroos/react-native-idfa#31]
Please upload your new releases to npm. They are not available there. Version `3.0.1` is the newest there: https://www.npmjs.com/package/@ptomasroos/react-native-idfa

**Comment by ptomasroos** [comment]
Please move to the following package name as using a @ sign will be deprecated in gradle 5.0
https://www.npmjs.com/package/react-native-idfa

Hence the package has been moved within npm
