### ISSUE TITLE
Getting NULL IDFA

### ISSUE THREAD

**Issue by muhammadwarisali** [ptomasroos/react-native-idfa#33]
I am getting null IDFAs for 50% of my clients. Any idea?
All iOS

**Comment by ptomasroos** [comment]
On Android or IOS primarly?
Clients are allowed to deny it by changing their settings

**Comment by muhammadwarisali** [comment]
They are all iOS. Havent launched the app on playstore yet. 
Is it possible that every 100 of 200 clients have denied (changed their setting). 
Just wanted to confirm if its a common practice in US (most of my client base is in US)

**Comment by ptomasroos** [comment]
Seems unlikely tbh. I dont live in the US so no clue.
