### ISSUE TITLE
Getting null when calling the idfa

### ISSUE THREAD

**Issue by IamNotHuman** [ptomasroos/react-native-idfa#47]
When I run on IOS Simulator I get the typical 0000 mask and when I run it on my Iphone with the advertising option enabled I get null, using react-native-idfa@4.1.0 and react-native@0.60.5

Does it have something to do with this?
<img width="613" alt="Captura de Pantalla 2020-04-06 a la(s) 11 47 14" src="https://user-images.githubusercontent.com/27880211/78583460-7cf33900-77fc-11ea-9f40-89fd7d862082.png">

**Comment by bsonmez** [comment]
I guess no support anymore. Having the same issue as well. Return empty string

**Comment by kasterlod** [comment]
It's working well with real device

**Comment by mynameisguy** [comment]
Not working for me on a real device.
iOS 14, RN 0.62

keep getting an empty string. any suggestions?

**Comment by bsonmez** [comment]
> Not working for me on a real device.
> iOS 14, RN 0.62
> 
> keep getting an empty string. any suggestions?

If I'm not mistaken, Apple forbade using IDFA since iOS 14.

**Comment by mynameisguy** [comment]
> > Not working for me on a real device.
> > iOS 14, RN 0.62
> > keep getting an empty string. any suggestions?
> 
> If I'm not mistaken, Apple forbade using IDFA since iOS 14.

Not yet, should work until 2021.
Other apps like DeviceId by AppsFlyer shows me my IDFA
