### ISSUE TITLE
Enable bitcode

### ISSUE THREAD

**Issue by rpavlovs** [ptomasroos/react-native-idfa#8]
Hi,

Is there a reason for disabling Bitcode?

I'm getting a linking error when trying to run on a device, that is resolved by enabling Bitcode in IDFA project.

**Comment by ptomasroos** [comment]
Hi there! Thanks for reporting the issue.

Let me look into it if we can enable it or not.

**Comment by javiercr** [comment]
Ran into the same issue today!

**Comment by ptomasroos** [comment]
This is now merged, feel free to use the hash in your npm package or wait for a release

**Comment by ptomasroos** [comment]
ceb0861e37bf5f0f1c58e9e7be17b95532ae023c

**Comment by rpavlovs** [comment]
Awesome! Thank you
